name: anim_search_app_bar
description: A flutter package that has an animated search bar with loads of customization
version: 1.0.0
homepage: https://github.com/Mto292/search_app_bar.git


environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter: